def um():
    print('                                                              ')
    print('                                                              ')
    print('          _______________            _______________          ')
    print('         |UUUUUUUMMMNNNNN\          /UUUUMMMMNNNNNNN|         ')
    print('         |UUUUUUUMMMNNNNNN\        /UUUUUUMMMNNNNNNN|         ')
    print('         |UUUUUUUMMMNNNNNNN\      /UUUUUUUMMMNNNNNNN|         ')
    print('           |UUUUUMMMNNNNNNNN\    /UUUUUUUUMMMNNNNN|           ')
    print('           |UUUUUMMMNNNNNNNNN\__/UUUUUUUUUMMMNNNNN|           ')
    print('           |UUUUUMMMNNNNMMUUUUUMMMMMMMUUUUMMMNNNNN|           ')
    print('           |UUUUUMMMNNNNMMUUUUUMMMMMMMUUUUMMMNNNNN|           ')
    print('           |UUUUUMMMNNNNNMUUUUUMMNNNNMUUUUMMMNNNNN|           ')
    print('           |UUUUUMMMNN|  \MUUUUMMNNN/  |UUMMMNNNNN|           ')
    print('           |UUUUUMMMNN|   \MUUUMMNN/   |UUMMMNNNNN|           ')
    print('           |UUUUUMMMNN|    \MUUMMN/    |UUMMMNNNNN|           ')
    print('           |UUUUUMMMNN|     \MUMN/     |UUMMMNNNNN|           ')
    print('          _|UUUUUMMMNN|_     \MN/     _|UUMMMNNNNN|_          ')
    print('         |UUUUUUUMMMNNNN|     \/     |UUUUMMMNNNNNNN|         ')
    print('         |UUUUUUUMMMNNNN|  UM FLINT  |UUUUMMMNNNNNNN|         ')
    print('         |UUUUUUUMMMNNNN|  COMP SCI  |UUUUMMMNNNNNNN|         ')
    print('         |UUUUUUUMMMNNNN|  RESEARCH  |UUUUMMMNNNNNNN|         ')
    print('                                                              ')
    print('                                                              ')
    print('                                                              ')

if __name__ == '__main__':
    um()
